// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2fAIz7qsS1Pq_aR4JTsVgszomdZOylvU',
    appId: '1:87991019896:web:64d24e70d6e6a1f63fc08d',
    messagingSenderId: '87991019896',
    projectId: 'volunteermatch-73b1d',
    authDomain: 'volunteermatch-73b1d.firebaseapp.com',
    storageBucket: 'volunteermatch-73b1d.firebasestorage.app',
    measurementId: 'G-55XY1ZSB44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXb_ISPeAoeGQkJu6x-uneV9rLQf1M35c',
    appId: '1:87991019896:android:10b8fca4f4c36fc03fc08d',
    messagingSenderId: '87991019896',
    projectId: 'volunteermatch-73b1d',
    storageBucket: 'volunteermatch-73b1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYbAO3T9D5qY7IcazDr9c6mAo2x4Zrqnw',
    appId: '1:87991019896:ios:cb83081abbf92fd03fc08d',
    messagingSenderId: '87991019896',
    projectId: 'volunteermatch-73b1d',
    storageBucket: 'volunteermatch-73b1d.firebasestorage.app',
    iosBundleId: 'com.example.volunteerMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYbAO3T9D5qY7IcazDr9c6mAo2x4Zrqnw',
    appId: '1:87991019896:ios:cb83081abbf92fd03fc08d',
    messagingSenderId: '87991019896',
    projectId: 'volunteermatch-73b1d',
    storageBucket: 'volunteermatch-73b1d.firebasestorage.app',
    iosBundleId: 'com.example.volunteerMatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2fAIz7qsS1Pq_aR4JTsVgszomdZOylvU',
    appId: '1:87991019896:web:ff515d4df72831553fc08d',
    messagingSenderId: '87991019896',
    projectId: 'volunteermatch-73b1d',
    authDomain: 'volunteermatch-73b1d.firebaseapp.com',
    storageBucket: 'volunteermatch-73b1d.firebasestorage.app',
    measurementId: 'G-19YS32NH4Y',
  );
}
